name: fitness_tracker
description:"A fitness tracking application."
publish_to: 'none'
environment:
  sdk: '>=3.3.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  go_router: ^14.2.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
